#%RAML 1.0 Library

uses:
  filter: https://raw.githubusercontent.com/VEuPathDB/EdaCommon/main/schema/filter.raml

types:

  EntityCountPostRequest:
    additionalProperties: false
    properties:
      filters:
        type: array
        items: filter.API_Filter

  EntityCountPostResponse:
    additionalProperties: false
    properties:
      count: integer

  VariableDistributionPostRequest:
    additionalProperties: false
    properties:
      filters:
        type: array
        items: filter.API_Filter

  VariableDistributionPostResponse:
    additionalProperties: false
    properties:
      entitiesCount:
        type: integer
        minimum: 0
      distribution:
        type: object
        properties:
          //: integer

  EntityTabularPostRequest:
    additionalProperties: false
    properties:
      outputVariableIds: string[]
      filters:
        type: array
        items: filter.API_Filter

  EntityTabularPostResponse:
    additionalProperties: false
    properties:
      counts: string[][]
