#%RAML 1.0 Library

uses:
  filter: ./filter.raml

types:

  Filters:
    type: array
    items: filter.API_Filter

  EntityCountPostRequest:
    additionalProperties: false
    properties:
      filters: Filters

  EntityCountPostResponse:
    additionalProperties: false
    properties:
      count: integer

  VariableDistributionPostRequest:
    additionalProperties: false
    properties:
      filters: Filters

  VariableDistributionPostResponse:
    additionalProperties: false
    properties:
      entitiesCount:
        type: integer
        minimum: 0
      distribution:
        type: object
        properties:
          //: integer

  EntityTabularPostRequest:
    additionalProperties: false
    properties:
      outputVariableIds: string[]
      filters: Filters

  EntityTabularPostResponse:
    additionalProperties: false
    properties:
      counts: string[][]
