#%RAML 1.0 Library

types:
# Type name determines the name of the Java class that will be generated.

  SingleNumericVarReductionConfig:
    properties:
      inputVariable: VariableSpec
      imputeZero?: boolean

  ConcatenationConfig:
    properties:
      prefix?: string
      delimiter?: string
      suffix?: string
      inputVariables: VariableSpec[]

  CategoricalRecodingRule:
    properties:
      inputValues: string[]
      outputValue: string

  CategoricalRecodingConfig:
    properties:
      inputVariable: VariableSpec
      rules: CategoricalRecodingRule[]
      unmappedValue?: string

  ContinuousNumericRule:
    properties:
      minInclusive?: number
      maxExclusive?: number
      outputValue: string

  ContinuousNumericRecodingConfig:
    properties:
      inputVariable: VariableSpec
      rules: ContinuousNumericRule[]
      imputeZero?: boolean
      unmappedValue?: string

  BodyMassIndexConfig:
    properties:
      heightVariable: VariableSpec
      weightVariable: VariableSpec
