#%RAML 1.0 Library

types:
# Type name determines the name of the Java class that will be generated.

  SingleNumericVarReductionConfig:
    properties:
      inputVariable: VariableSpec
      imputeZero?: boolean

  ConcatenationConfig:
    properties:
      prefix?: string
      delimiter?: string
      suffix?: string
      inputVariables: VariableSpec[]

  CategoricalRecodingRule:
    properties:
      inputValues: string[]
      outputValue: string

  CategoricalRecodingConfig:
    properties:
      inputVariable: VariableSpec
      rules: CategoricalRecodingRule[]
      unmappedValue?: string

  ContinuousNumericRule:
    properties:
      minInclusive?: number
      maxExclusive?: number
      outputValue: string

  ContinuousNumericRecodingConfig:
    properties:
      inputVariable: VariableSpec
      rules: ContinuousNumericRule[]
      imputeZero?: boolean
      unmappedValue?: string

  BodyMassIndexConfig:
    properties:
      heightVariable: VariableSpec
      weightVariable: VariableSpec

  SubsetMembershipConfig:
    properties:
      subsetFilters: API_Filter[]

  UnitConversionConfig:
    properties:
      inputVariable: VariableSpec
      outputUnits: string

  VariableReference:
    properties:
      name: string
      variable: VariableSpec

  AdvancedSubsetInputVar:
    type: VariableReference
    properties:
      trueValues?: string[]   # defaults to [ '1', 'true', 'yes' ]

  SetOperation:
    properties:
      operation:
        type: string
        enum: [ 'intersect', 'union', 'minus' ]
      # caller must pick one left and one right; needed since union types are unsupported
      leftOperation?: SetOperation
      leftVariable?: string
      rightOperation?: SetOperation
      rightVariable?: string

  AdvancedSubsetConfig:
    properties:
      operationTree: SetOperation
      inputVariables: AdvancedSubsetInputVar[]

  EcmaScriptExpressionEvalConfig:
    properties:
      ecmaScriptExpression: string
      inputVariables: VariableReference[]
      expectedType: API_VariableType
      expectedShape: API_VariableDataShape

  RelatedObservationMinTimeIntervalConfig:
    properties:
      relatedObservationsSubset: API_Filter[]
      anchorVariable: VariableSpec
      anchorVariableTrueValues: string[]
      anchorTimestampVariable: VariableSpec
      targetVariable: VariableSpec
      targetVariableTrueValues: string[]
      targetTimestampVariable: VariableSpec
      minimumTimeIntervalDays: integer
