#%RAML 1.0 Library

types:

  EntityCountPostRequest:
    additionalProperties: false
    properties:
      filters: API_Filter[]

  EntityCountPostResponse:
    additionalProperties: false
    properties:
      count: integer

  VariableDistributionPostRequest:
    additionalProperties: false
    properties:
      filters: API_Filter[]

  VariableDistributionPostResponse:
    additionalProperties: false
    properties:
      entitiesCount:
        type: integer
        minimum: 0
      distribution:
        type: object
        properties:
          //: integer

  API_PagingConfig:
    type: object
    properties:
      numRows: integer
      offset: integer

  API_TabularReportConfig:
    type: object
    properties:
      sortingColumns?: string[]
      pagingConfig?: API_PagingConfig

  EntityTabularPostRequest:
    additionalProperties: false
    properties:
      filters: API_Filter[]
      outputVariableIds: string[]
      reportConfig?: API_TabularReportConfig

  EntityTabularPostResponse:
    additionalProperties: false
    properties:
      counts: string[][]
