#%RAML 1.0 Library

types:

  StudiesGetResponse:
    additionalProperties: false
    properties:
      studies: API_StudyOverview[]

  StudyIdGetResponse:
    additionalProperties: false
    properties:
      study: API_StudyDetail

  API_StudyOverview:
    type: object
    properties:
      id: string
      datasetId: string

  EntityIdGetResponse:
    type: API_Entity

  API_StudyDetail:
    type: API_StudyOverview
    properties:
      rootEntity: API_Entity
      units: UnitsGroup[]
      scale: ScaleOption[]

  UnitsGroup:
    type: object
    properties:
      unitsGroupId: string
      displayName: string
      members: UnitOption[]

  UnitOption:
    type: object
    properties:
      unitsId: string
      displayName: string

  ScaleOption:
    type: object
    properties:
      scaleId: string
      displayName: string

  VariableAspect:
    type: object
    properties:
      id: string
      display: string

  API_Entity:
    type: object
    properties:
      id: string
      idColumnName: string
      displayName: string
      displayNamePlural: string
      description: string
      children?: API_Entity[]
      variables: API_Variable[]

  API_Variable:
    type: object
    discriminator: type
    properties:
      id: string
      providerLabel: string
      displayName: string
      parentId?: string
      type: API_VariableType
      isMultiValued: boolean
      displayType: API_VariableDisplayType
      dataShape: API_VariableDataShape
      isFeatured: boolean
      isTemporal: boolean
      unitsGroupId: string
      defaultUnitsId: string
      defaultScaleId: string

  API_VariableType:
    enum: [ 'category', 'string', 'number', 'date', 'longitude' ]

  API_VariableDataShape:
    enum: [ 'continuous', 'categorical', 'ordinal', 'binary' ]

  API_VariableDisplayType:
    enum: [ 'default', 'multifilter', 'hidden' ]

  API_VariablesCategory:
    type: API_Variable
    discriminatorValue: category

  API_StringVariable:
    type: API_Variable
    discriminatorValue: string

  API_NumberVariable:
    type: API_Variable
    discriminatorValue: number
    properties:
      precision: integer
      defaultScaleId: string

  API_DateVariable:
    type: API_Variable
    discriminatorValue: date

  API_LongitudeVariable:
    type: API_Variable
    discriminatorValue: longitude

