#%RAML 1.0 Library

types:

  StudiesGetResponse:
    additionalProperties: false
    properties:
      studies: API_StudyOverview[]

  StudyIdGetResponse:
    additionalProperties: false
    properties:
      study: API_StudyDetail

  API_StudyOverview:
    type: object
    properties:
      id: string

  EntityIdGetResponse:
    type: API_Entity

  API_StudyDetail:
    type: object
    properties:
      id: string
      rootEntity: API_Entity

  API_Entity:
    type: object
    properties:
      id: string
      idColumnName: string
      displayName: string
      displayNamePlural: string
      description: string
      children?: API_Entity[]
      variables: API_Variable[]
      collections: API_Collection[]

  # a way to ensure collection type and all child var types match? or just manual validation?
  API_Collection:
    type: object
    discriminator: type
    properties: 
      id: string
      displayName: string
      description: string
      vocabulary?: string[]
      distinctValuesCount: number
      type: API_CollectionType
      variables: API_Variable[]
  
  API_CollectionType:
    enum: [ 'number', 'date', 'integer' ]

  API_NumberCollection:
    type: API_Collection
    discriminatorValue: number
    properties:
      units: string
      precision: number
      displayRangeMin?: number
      displayRangeMax?: number
      rangeMin?: number
      rangeMax?: number
      binWidthOverride?: number

  API_IntegerCollection:
    type: API_Collection
    discriminatorValue: integer
    properties:
      units: string
      displayRangeMin?: integer
      displayRangeMax?: integer
      rangeMin?: integer
      rangeMax?: integer
      binWidthOverride?: integer

  API_DateCollection:
    type: API_Collection
    discriminatorValue: date
    properties:
      displayRangeMin?: string
      displayRangeMax?: string
      rangeMin?: string
      rangeMax?: string
      binWidthOverride?: number
      binUnits?: BinUnits

  API_Variable:
    type: object
    discriminator: type
    properties:
      id: string
      parentId?: string
      providerLabel: string
      displayName: string
      definition?: string
      displayType: API_VariableDisplayType
      displayOrder?: number
      isCategory: string
      type: API_VariableType
      hideFrom: string[]

  API_VariableWithValues:
    type: API_Variable
    properties:
      dataShape?: API_VariableDataShape
      vocabulary?: string[]
      distinctValuesCount: number
      isTemporal: boolean
      isFeatured: boolean
      isMergeKey: boolean
      isMultiValued: boolean

  API_VariableType:
    enum: [ 'category', 'string', 'number', 'date', 'longitude', 'integer' ]

  API_VariableDataShape:
    enum: [ 'continuous', 'categorical', 'ordinal', 'binary' ]

  API_VariableDisplayType:
      enum: [ 'default', 'multifilter', 'hidden' ]

  API_VariablesCategory:
    type: API_Variable
    discriminatorValue: category

  API_StringVariable:
    type: API_VariableWithValues
    discriminatorValue: string

  API_LongitudeVariable:
    type: API_VariableWithValues
    discriminatorValue: longitude
    properties:
      precision: number

  API_NumberVariable:
    type: API_VariableWithValues
    discriminatorValue: number
    properties:
      units: string
      precision: number
      displayRangeMin?: number
      displayRangeMax?: number
      rangeMin?: number
      rangeMax?: number
      binWidth?: number
      binWidthOverride?: number

  API_IntegerVariable:
    type: API_VariableWithValues
    discriminatorValue: integer
    properties:
      units: string
      displayRangeMin?: integer
      displayRangeMax?: integer
      rangeMin?: integer
      rangeMax?: integer
      binWidth?: integer
      binWidthOverride?: integer

  API_DateVariable:
    type: API_VariableWithValues
    discriminatorValue: date
    properties:
      displayRangeMin?: string
      displayRangeMax?: string
      rangeMin?: string
      rangeMax?: string
      binWidth?: number
      binWidthOverride?: number
      binUnits?: BinUnits
  
  # not sure where to put this. 
  # think maybe this is what the data service will consume rather than VariableSpec?
  CollectionSpec:
    additionalProperties: false
    properties:
      entityId: string
      collectionId: string
